# Generated by Django 5.2.7 on 2025-11-03 08:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('decs', models.TextField()),
                ('image', models.FileField(upload_to='image/category')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('icon', models.FileField(upload_to='image/flag')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image/sevices')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=190)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('main_image', models.FileField(upload_to='images/product')),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'yellow'), ('orange', 'Orange'), ('purlple', 'Purple'), ('pink', 'Pink'), ('gray', 'Gray')], default='white', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('guarantee', models.PositiveSmallIntegerField(default=1)),
                ('delivery_time', models.CharField(choices=[('1_day', '1 Day Delivery'), ('2_days', '2 Days Delivery'), ('3_4_days', '3–4 Days Delivery'), ('5_7_days', '5–7 Days Delivery'), ('10_14_days', '10–14 Days Delivery'), ('2_3_weeks', '2–3 Weeks Delivery'), ('3_4_weeks', '3–4 Weeks Delivery'), ('1_month', '1 Month Delivery'), ('2_months', '2 Months Delivery')], default='2_days', max_length=50)),
                ('rewiew', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(blank=True, choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('L', 'Large'), ('xl', 'Extra Large'), ('xxl', '2x Large'), ('one_size', 'One Size'), ('Custom', 'Custom Size')], max_length=100, null=True)),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('recomended', models.BooleanField(default=False)),
                ('company', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coutry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.country')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='image/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image/sub-category')),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'yellow'), ('orange', 'Orange'), ('purlple', 'Purple'), ('pink', 'Pink'), ('gray', 'Gray')], default='green', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='main.subcategory'),
        ),
    ]
