# Generated by Django 5.2.7 on 2025-11-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rewiew',
            new_name='review',
        ),
    ]
