# Generated by Django 5.2.7 on 2025-11-06 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_rewiew_product_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coutry',
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
    ]
