# Generated by Django 5.2.7 on 2025-11-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_category_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
